FROM node:alpine

WORKDIR './app'

COPY package.json ./

RUN npm install && npm cache verify
RUN rm -rf node_modules/sharp
RUN npm install --arch=x64 --platform=linux --target=10.16.0 sharp

COPY . .

CMD ["npm", "run", "dev"]
